---
title: <font size="6">**Matthew S. Dettman, ChFC, CLU**</font>
---


<font size="5"><u>**Education and Professional Certificates**</u></font>


<font size="3">**Master of Science in Business Data Analytics** | West Virginia University | 2021 | **GPA 4.0**</font>

 - R Programming for Advanced Statistics, Machine Learning, Statistical Modeling, Database Design, Decision Sciences, Visualizations, Simulations, Algorithms, and Data Visualization.  


<font size="3">**Bachelor of Science in Business Administration**</font> | Glenville State University | 2007 
 
 - Quantitative Business Analysis, Statistics, Business Law, and Computing Concepts.

<font size="3">**Chartered Financial Consultant**</font> | The American College of Financial Services | 2015 
 
 - Planning for Retirement Needs, Investments, and Applications in Financial Planning

<font size="3">**Chartered Life Underwriter **</font> | The American College of Financial Services | 2015

 - Individual Life Insurance, Planning for Business Owners and Professionals, Life Insurance Law.

<font size="3">**Financial Industry Regulatory Authority**</font> | [FINRA CRD # 5819922](https://brokercheck.finra.org/individual/summary/5819922) | *Not Currently Registered*

 - Series 7 – General Securities Representative:  Corporate Securities, Municipal Securities, Options, and ETFs.
 - Series 66 – Uniform Combined State Law:  Regulatory Compliance for Investment Advisors.  
 - Series 24 – General Securities Principal:  Supervision of General Broker-Dealer Activities
 - Series 52 – Municipal Securities Representative:  Fundamentals of Municipal Securities Trading.
 - Series 53 – Municipal Securities Principal:  Management of Municipal Securities Activities.
 - Series 4 – Registered Options Principal:  Supervision of General Options Activities and Trading.


<font size="5"><u>**Technical Skills**</u></font>


 - **Programming Languages and Software**:  R Statistical/Scripting Language, RStudio, RMarkdown, and some Shiny.  
 - **Statistics and Modeling**:  Linear, regression, machine learning, time-series analysis, and forecasting.
 - **Reporting**:  Reproducible HTML documents, websites, and PDFs containing R, Python, and SQL code. 




<font size="5"><u>**Professional Experience**</u></font>

 

<font size="3">**Sr. Data Integrity Analyst**</font> | Advisor Group | 05/2021 - 12/2021  



<font size="3">**Regional Supervision Director**</font> | Advisor Group | 01/2019 – 05/2021



<font size="3">**Regional Supervision Manager**</font> | Advisor Group | 08/2017 - 01/2019


<font size="3">**Branch Office Examiner**</font> | Advisor Group | 04/2015 - 01/2017  


<font size="3">**Sr. Investment Service Specialist**</font> | Edward Jones | 07/2011 - 04/2015


<br/>


<br/>



*Document Built with R Version: `r getRversion()`*


