---
title: "S&P 500 Sectors "
---



<br/>



```{r Sector_Grid,  fig.height = 6, out.width='100%', echo=FALSE, warning=FALSE, message=FALSE}

# Libraries Used 
library(tidyverse) # Core Data Analysis Tools
library(tidyquant) # Quantitative Analysis
library(plotly)    # Interactive Visualizations
library(timetk)    # Time Series Tools


## Create a character string of the symbols we want to analyze. 
sector_prices <- c( 

"^GSPC",     #  S&P 500 Index
"^GSPE",     #  S&P 500 Energy 	
"^SP500-40", #	S&P 500 Financials 	
"^SP500-35", #  S&P 500 Health Care	
"^SP500-60", #  S&P Real Estate
"^SP500-15", #	S&P 500 Materials	
"^SP500-20", #	S&P 500 Industrials
"^SP500-25", #	S&P 500 Consumer Discretionary
"^SP500-30", #  S&P 500 Consumer Staples
"^SP500-45", #	S&P 500 Information Technology
"^SP500-50", #	S&P 500 Telecommunication Services
"^SP500-55"  #  S&P 500 Utilities

  )  %>%
  
  ## Request the data from Yahoo Finance.  
  tq_get(get = "stock.prices", from = (today()-365))


## Create a tribble to be used as a lookup table.
sector_list <- tribble(
  
  ~ symbol,  ~ IndexName,
  "^GSPC",     "SP500",                   # S&P 500 Index
  "^GSPE",     "Energy",                  # S&P 500 Energy 	  
  "^SP500-40", "Financials",	            # S&P 500 Real Estate	
  "^SP500-35", "HealthCare",              # S&P 500 Materials	
  "^SP500-60", "RealEstate",	            # S&P Real Estate
  "^SP500-15", "Materials",	              # S&P Materials
  "^SP500-20", "Industrials",             # S&P Industrials
  "^SP500-25", "ConsumerDiscretionary",   # S&P Consumer Discretionary
  "^SP500-30", "ConsumerStaples",         # S&P Consumer Staples
  "^SP500-45", "InformationTechnology",   # S&P Information Technology
  "^SP500-50", "CommunicationServices",   # S&P Communication Services
  "^SP500-55", "Utilities")               # S&P Utilities


## Join the prices and names so the data is ready for visualization.  
SECTORS <- sector_prices %>% left_join(sector_list,by="symbol")

SECTORS %>%
  group_by(IndexName) %>%
  plot_time_series(date, close, 
                   .facet_scales = "free",
                   .interactive = TRUE,
                   .plotly_slider = FALSE,
                   .facet_ncol = 3,
                   .title = "Recent S&P 500 Sector Closing Prices (1 Year)")
                   
```

Data Source:  [Yahoo](https://finance.yahoo.com/)

<br/>


<br/>


```{r Sector_Grid2,  fig.height = 6, out.width='100%', echo=FALSE, warning=FALSE, message=FALSE}
SECTORS %>% 
  filter(date >= (today()-30)) %>% 
  group_by(IndexName) %>%
  plot_time_series(date, close, 
                   .facet_scales = "free",
                   .interactive = TRUE,
                   .plotly_slider = FALSE,
                   .facet_ncol = 3,
                   .title = "Recent S&P 500 Sector Closing Prices (30 Days)")
                   
```  
Data Source:  [Yahoo](https://finance.yahoo.com/)


<br/>




<br/>



*Data last refreshed on `r Sys.Date()`.*

*Document Built with R Version: `r getRversion()`*



